import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/posts/first-post">Link</Link>

      <Image
        src="/images/profile.jpeg"
        height={144}
        width={144}
        alt="Your Name"
      />
    </div>
  );
}
